/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

/**
 *
 * @author elviAle
 */
public class MenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        JdEscritorio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        mArchivo = new javax.swing.JMenu();
        mSalir = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        MitemformAlumnos = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        MitemMaterias = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        MitemCursadas = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        MitemInscripciones = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        MitemListados = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenu7 = new javax.swing.JMenu();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        JdEscritorio.setBackground(new java.awt.Color(255, 255, 102));

        javax.swing.GroupLayout JdEscritorioLayout = new javax.swing.GroupLayout(JdEscritorio);
        JdEscritorio.setLayout(JdEscritorioLayout);
        JdEscritorioLayout.setHorizontalGroup(
            JdEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 549, Short.MAX_VALUE)
        );
        JdEscritorioLayout.setVerticalGroup(
            JdEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 304, Short.MAX_VALUE)
        );

        mArchivo.setText("Archivo");

        mSalir.setText("Salir");
        mArchivo.add(mSalir);

        jMenuBar1.add(mArchivo);

        jMenu2.setText("Alumno");

        MitemformAlumnos.setText("Formulario Alumnos");
        MitemformAlumnos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MitemformAlumnosActionPerformed(evt);
            }
        });
        jMenu2.add(MitemformAlumnos);

        jMenuBar1.add(jMenu2);

        jMenu1.setText("Marteria");

        MitemMaterias.setText("Formulario Materias");
        jMenu1.add(MitemMaterias);

        jMenuBar1.add(jMenu1);

        jMenu3.setText("Cursada");

        MitemCursadas.setText("Formulario Cursadas");
        jMenu3.add(MitemCursadas);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Inscripciones");

        MitemInscripciones.setText("Formulario Inscripciones");
        jMenu4.add(MitemInscripciones);

        jMenuBar1.add(jMenu4);

        jMenu5.setText("Listados");

        MitemListados.setText("Formulario Listados");
        jMenu5.add(MitemListados);

        jMenuBar1.add(jMenu5);

        jMenu6.setText("Carga de Notas");
        jMenuBar1.add(jMenu6);

        jMenu7.setText("Consulta");
        jMenuBar1.add(jMenu7);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(JdEscritorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JdEscritorio)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MitemformAlumnosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MitemformAlumnosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MitemformAlumnosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane JdEscritorio;
    private javax.swing.JMenuItem MitemCursadas;
    private javax.swing.JMenuItem MitemInscripciones;
    private javax.swing.JMenuItem MitemListados;
    private javax.swing.JMenuItem MitemMaterias;
    private javax.swing.JMenuItem MitemformAlumnos;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenu mArchivo;
    private javax.swing.JMenuItem mSalir;
    // End of variables declaration//GEN-END:variables
}
